name: frontent secret-santa deploy workflow

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  cd:
    runs-on: ubuntu-latest

    env:
      VITE_AUTH_SERVICE_BACKEND_URL: ${{secrets.VITE_AUTH_SERVICE_BACKEND_URL}}
      VITE_NAME: ${{secrets.VITE_NAME}}
      VITE_REGISTER_DEADLINE: ${{secrets.VITE_REGISTER_DEADLINE}}
      WORKING_DIR: frontend
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_REGION: "us-east-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing packages
        run: npm install
        working-directory: ./${{ env.WORKING_DIR }}

      - name: Building the app
        run: npm run build
        working-directory: ./${{ env.WORKING_DIR }}

      - name: Uploading the app
        run: aws s3 sync . s3://ioet-secret-santa/ --delete
        working-directory: ./${{ env.WORKING_DIR }}/dist
